routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Frontend Routes
Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
  Route::get('/', 'ProductController@show')->name('all');
  Route::get('/{product}','ProductController@singlepro')->name('singlepro');
  Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('addToCart');
});


// Admin Panel Route
Route::group(['as' => 'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function () {
  Route::get('category/{category}/remove', 'CategoryController@remove')->name('category.remove');
  Route::get('category/trash', 'CategoryController@trash')->name('category.trash');
  Route::get('category/recover/{id}', 'CategoryController@recoverCat')->name('category.recover');
  Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');

  Route::get('product/{product}/remove', 'ProductController@remove')->name('product.remove');
  Route::get('product/trash', 'ProductController@trash')->name('product.trash');
  Route::get('product/recover/{id}', 'ProductController@recoverProduct')->name('product.recover');

  Route::view('product/extras', 'admin.partials.extras')->name('product.extras');

  Route::get('profile/{profile}/remove', 'ProfileController@remove')->name('profile.remove');
  Route::get('profile/trash', 'ProfileController@trash')->name('profile.trash');
  Route::get('profile/recover/{id}', 'ProfileController@recoverprofile')->name('profile.recover');
  Route::view('profile/roles', 'admin.partials.extras')->name('profile.extras');

  Route::get('profile/states/{id?}', 'ProfileController@getStates')->name('profile.states');
  Route::get('profile/cities/{id?}', 'ProfileController@getCities')->name('profile.cities');

  Route::resource('product', 'ProductController');
  Route::resource('category', 'CategoryController');
  Route::resource('profile', 'ProfileController');
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Category;

class Product extends Model
{
  use SoftDeletes;
  protected $guarded = [];
  protected $dates = ['deleted_at'];
  //

  public function categories()
  {
    return $this->belongsToMany("App\Category");
  }
  public function getRouteKeyName()
  {
    return 'slug';
  }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;
use App\Category;
use App\Http\Requests\StoreProduct;
use Illuminate\Support\Facades\Storage;
use App\Cart;
use Session;

class ProductController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    // $product = Product::all();
    $products = Product::with('categories')->paginate(3);
    return view('admin.products.index', compact('products'));
  }

  /**
   * Display Trashed listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function trash()
  {
    $products = Product::with('categories')->onlyTrashed()->paginate(3);
    return view('admin.products.index', compact('products'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $categories = Category::with('childrens')->get();
    return view('admin.products.create', compact('categories'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(StoreProduct $request)
  {
    $path = 'images/no-thumbnail.jpeg';
    if ($request->has('thumbnail')) {
      $extension = "." . $request->thumbnail->getClientOriginalExtension();
      $name = basename($request->thumbnail->getClientOriginalName(), $extension) . time();
      $name = $name . $extension;
      $path = $request->thumbnail->storeAs('images', $name, 'public');
    }
    $product = Product::create([
      'title' => $request->title,
      'slug' => $request->slug,
      'description' => $request->description,
      'thumbnail' => $path,
      'status' => $request->status,
      'options' => isset($request->extras) ? json_encode($request->extras) : null,
      'featured' => ($request->featured) ? $request->featured : 0,
      'price' => $request->price,
      'discount' => $request->discount ? $request->discount : 0,
      'discount_price' => ($request->discount_price) ? $request->discount_price : 0,
    ]);
    if ($product) {
      $product->categories()->attach($request->category_id, ['created_at' => now(), 'updated_at' => now()]);
      return back()->with('message', 'Product Successfully Added');
    } else {
      return back()->with('message', 'Error Inserting Product');
    }
  }
  /**
   * Display the specified resource.
   *
   * @param  \App\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function show(Product $product)
  {
    $categories = Category::all();
    $products = Product::all();
    return view('products.all', compact('categories', 'products'));
  }

  public function singlepro(Product $product)
  {
    return view('products.singlepro', compact('product'));
  }

  public function addToCart(Product $product, Request $request)
  {
    dd(Session::get('cart'));
    $oldCart = Session::has('cart') ? Session::get('cart') : null;
    $qty = $request->qty ? $request->qty : 1;
    $cart = new Cart($oldCart);
    $cart->addProduct($product, $qty);
    Session::put('cart', $cart);
    return back()->with('message', "Product $product->title has been successfully added to cart");

  }
  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function edit(Product $product)
  {
    $categories = Category::all();
    return view('admin.products.create', compact('product', 'categories'));
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Product $product)
  {
    if ($request->has('thumbnail')) {
      $extension = "." . $request->thumbnail->getClientOriginalExtension();
      $name = basename($request->thumbnail->getClientOriginalName(), $extension) . time();
      $name = $name . $extension;
      $path = $request->thumbnail->storeAs('images', $name);
      $product->thumbnail = $path;
    }
    $product->title = $request->title;
    // $product->slug = $request->slug;
    $product->description = $request->description;
    $product->status = $request->status;
    $product->options = isset($request->extras) ? json_encode($request->extras) : null;
    $product->featured = ($request->featured) ? $request->featured : 0;
    $product->price = $request->price;
    $product->discount = $request->discount ? $request->discount : 0;
    $product->discount_price = ($request->discount_price) ? $request->discount_price : 0;

    $product->categories()->detach();

    if ($product->save()) {
      $product->categories()->attach($request->category_id);
      return back()->with('message', 'Product Updated Successfully!!');
    } else {
      return back()->with('message', 'Error !! Product Can not Updated !!');
    }
  }

  public function recoverProduct($id)
  {
    $product = Product::onlyTrashed()->findOrFail($id);
    if ($product->restore()) {
      return back()->with('message', 'Product Successfully Deleted!');
    } else {
      return back()->with('message', 'Errors from deleted item!');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Product  $product
   * @return \Illuminate\Http\Response
   */
  public function destroy(Product $product)
  {
    if ($product->categories()->detach() && $product->forceDelete()) {
      Storage::delete($product->thumbnail);
      return back()->with('message', 'Product Successfully Deleted!');
    } else {
      return back()->with('message', 'Error Deleting Record');
    }
  }

  public function remove(Product $product)
  {
    if ($product->delete()) {
      return back()->with('message', 'Product Successfully Trashed!');
    } else {
      return back()->with('message', 'Error Deleting Product');
    }
  }
}

resources/views/admin/products/create.blade.php
@extends('admin.app') {{-- 
@section('breadcrumbs')
<li class="breadcrumb-item">
  <a href="{{route('admin.dashboard')}}">Dashboard</a>
</li>
<li class="breadcrumb-item">
  <a href="{{route('admin.category.index')}}">Categories</a>
</li>
<li class="breadcrumb-item active" aria-current="page">Add/Edit Category</li>
@endsection
 --}} 
@section('content')
</div>
<form action="@if(isset($product)) {{route('admin.product.update', $product)}} @else 
{{route('admin.product.store')}} @endif" method="POST" accept-charset="utf-8" enctype="multipart/form-data">
  <div class="row">
    @csrf @if (isset($product)) @method('PUT') @endif
    <div class="col-lg-9">
      <div class="form-group row">
        <div class="col-sm-12">
          @if ($errors->any())
          <div class="alert alert-danger">
            <ul>
              @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
              @endforeach
            </ul>
          </div>
          @endif
        </div>
        <div class="col-sm-12">
          @if (session()->has('message'))
          <div class="alert alert-success">
            {{session('message')}}
          </div>
          @endif
        </div>
        <div class="col-lg-12">
          <label class="form-control-label">Title: </label>
          <input type="text" id="txturl" name="title" class="form-control " value="{{@$product->title}}" />
          <p class="small">{{config('app.url')}}<span id="url">{{@$product->slug}}</span>
            <input type="hidden" name="slug" id="slug" value="{{@$product->slug}}">
          </p>
        </div>
      </div>
      <div class="form-group row">

        <div class="col-lg-12">
          <label class="form-control-label">Description: </label>
          <textarea name="description" id="editor" class="form-control ">{!! @$product->description !!}</textarea>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-6">
          <label class="form-control-label">Price: </label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">$</span>
            </div>
            <input type="text" class="form-control" name="price" placeholder="0.00" aria-label="Username" aria-describedby="basic-addon1"
              value="{{@$product->price}}" />
          </div>
        </div>
        <div class="col-6">
          <label class="form-control-label">Discount: </label>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" id="basic-addon1">$</span>
            </div>
            <input type="text" class="form-control" name="discount_price" placeholder="0.00" aria-label="discount_price" aria-describedby="discount"
              value="{{@$product->discount_price}}" />
          </div>
        </div>
      </div>
      <div class="form-group row">
        <div class="card col-sm-12 p-0 mb-2">
          <div class="card-header align-items-center">
            <h5 class="card-title float-left">Extra Options</h5>
            <div class="float-right">
              <button type="button" id="btn-add" class="btn btn-primary btn-sm">+</button>
              <button type="button" id="btn-remove" class="btn btn-danger btn-sm">-</button>
            </div>

          </div>
          <div class="card-body" id="extras">

          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
      <ul class="list-group row">
        <li class="list-group-item active">
          <h5>Status</h5>
        </li>
        <li class="list-group-item">
          <div class="form-group row">
            <select class="form-control" id="status" name="status">
						<option value="0" @if(isset($product) && $product->status == 0) {{'selected'}} @endif>Pending</option>
						<option value="1" @if(isset($product) && $product->status == 1) {{'selected'}} @endif>Publish</option>
					</select>
          </div>
          <div class="form-group row">
            <div class="col-lg-12">
              @if (isset($product))
              <input type="submit" name="submit" class="btn btn-primary btn-block " value="Update Product" /> @else
              <input type="submit" name="submit" class="btn btn-primary btn-block " value="Add Product" /> @endif
            </div>

          </div>
        </li>
        <li class="list-group-item active">
          <h5>Feaured Image</h5>
        </li>
        <li class="list-group-item">
          <div class="input-group mb-3">
            <div class="custom-file ">
              <input type="file" class="custom-file-input" name="thumbnail" id="thumbnail">
              <label class="custom-file-label" for="thumbnail">Choose file</label>
            </div>
          </div>
          <div class="img-thumbnail  text-center">
            <img src="@if(isset($product)) {{asset('storage/'.$product->thumbnail)}} @else 
            {{asset('images/no-thumbnail.jpeg')}} @endif" id="imgthumbnail" class="img-fluid" alt="">
          </div>
        </li>
        <li class="list-group-item">
          <div class="col-12">
            <div class="input-group mb-3">

              <div class="input-group-prepend">
                <span class="input-group-text"><input id="featured" type="checkbox" name="featured" value="@if(isset($product)){{@$product->featured}}@else{{0}}@endif" @if(isset($product) && $product->featured == 1) {{'checked'}} @endif /></span>
              </div>

              <p type="text" class="form-control" name="featured" placeholder="0.00" aria-label="featured" aria-describedby="featured">Featured Product</p>
            </div>
          </div>
        </li>
        @php $ids = (isset($product) && $product->categories->count() > 0) ? array_pluck($product->categories->toArray(), 'id') :
        null; 
@endphp
        <li class="list-group-item active">
          <h5>Select Categories</h5>
        </li>
        <li class="list-group-item ">
          <select name="category_id[]" id="select2" class="form-control" multiple>
            @if ($categories->count() > 0)
            @foreach ($categories as $category)
            <option value="{{$category->id}}"
              @if (!is_null($ids) && in_array($category->id, $ids))
                  {{'selected'}}
              @endif
              >{{$category->title}}</option>					
            @endforeach
            @endif
				</select>
        </li>
      </ul>
    </div>
  </div>
</form>
@endsection
 
@section('scripts')
<script type="text/javascript">
  $(function(){
			ClassicEditor.create( document.querySelector( '#editor' ), {
		toolbar: [ 'Heading', 'Link', 'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote','undo', 'redo' ],
	})
.then( editor => {
console.log( editor );
} )
.catch( error => {
console.error( error );
} );
<?php
if (!isset($product)) {
?>
		$('#txturl').on('keyup', function(){
			const pretty_url = slugify($(this).val());
			$('#url').html(slugify(pretty_url));
			$('#slug').val(pretty_url);
		})
<?php
  }
?>
		$('#select2').select2({
			placeholder: "Select multiple Categories",
		allowClear: true
		});

		
		$('#status').select2({
			placeholder: "Select a status",
		allowClear: true,
		minimumResultsForSearch: Infinity
		});
$('#thumbnail').on('change', function() {
var file = $(this).get(0).files;
var reader = new FileReader();
reader.readAsDataURL(file[0]);
reader.addEventListener("load", function(e) {
var image = e.target.result;
$("#imgthumbnail").attr('src', image);
});
});
$('#btn-add').on('click', function(e){
	
		var count = $('.options').length+1;
		$('#extras').append('<div class="row align-items-center options">\
						<div class="col-sm-4">\
												<label class="form-control-label">Option <span>'+count+'</span></label>\
												<input type="text" name="extra[\'option\'][]" class="form-control" value="" placeholder="size">\
						</div>\
						<div class="col-sm-8">\
												<label class="form-control-label">Values</label>\
												<input type="text" name="extra[\'values\'][]" class="form-control" placeholder="options1 | option2 | option3" />\
												<label class="form-control-label">Additional Prices</label>\
												<input type="text" name="extra[\'prices\'][]" class="form-control" placeholder="price1 | price2 | price3" />\
						</div>\
					</div>');
})
$('#btn-remove').on('click', function(e){
	
		if($('.options').length > 1){
			$('.options:last').remove();
		}
})

$('#featured').on('change', function() {
  if ($(this).is(":checked"))
    $(this).val(1)
    else
      $(this).val(0)
  })

})

</script>
@endsection

resources/views/admin/products/index.blade.php
@extends('admin.app') 
@section('content')
</div>
<div class="row pb-3">
  <div class="col-sm-12">
    <a href="{{route('admin.product.create')}}" class="btn btn-primary float-right">Add Product</a>
  </div>
</div>
<div class="row d-block">
  <div class="col-sm-12">
    @if (session()->has('message'))
    <div class="alert alert-success">
      {{session('message')}}
    </div>
    @endif
  </div>
</div>

<div class="table-responsive" style="scroll-direction: horizontal;">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Description</th>
        <th>Slug</th>
        <th>Categories</th>
        <th>Price</th>
        <th>Thumbnail</th>
        <th>Date Created</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      @if($products->count() > 0) @foreach($products as $product)
      <tr>
        <td>{{$product->id}}</td>
        <td>{{$product->title}}</td>
        <td>{!! $product->description !!}</td>
        <td>{{$product->slug}}</td>
        <td>
          @if($product->categories()->count() > 0) @foreach($product->categories as $children) {{$children->title}}, @endforeach @else
          <strong>{{"product"}}</strong> @endif
        </td>
        <td>${{$product->price}}</td>
        <td><img src="{{asset('storage/'.$product->thumbnail)}}" alt="{{$product->title}}" class="img-responsive" height="50"
          /></td>
        @if($product->trashed())
        <td>{{$product->deleted_at}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('admin.product.recover',$product->id)}}">Restore</a> | <a class="btn btn-danger btn-sm"
            href="javascript:;" onclick="confirmDelete('{{$product->id}}')">Delete</a>
          <form id="delete-product-{{$product->id}}" action="{{ route('admin.product.destroy', $product->slug) }}" method="POST" style="display: none;">

            @method('DELETE') @csrf
          </form>
        </td>
        @else
        <td>{{$product->created_at}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('admin.product.edit',$product->slug)}}">Edit</a> | <a id="trash-product-{{$product->id}}"
            class="btn btn-warning btn-sm" href="{{route('admin.product.remove',$product->slug)}}">Trash</a> | <a class="btn btn-danger btn-sm"
            href="javascript:;" onclick="confirmDelete('{{$product->slug}}')">Delete</a>
          <form id="delete-product-{{$product->slug}}" action="{{ route('admin.product.destroy', $product->slug) }}" method="POST"
            style="display: none;">

            @method('DELETE') @csrf
          </form>
        </td>
        @endif
      </tr>
      @endforeach @else
      <tr>
        <td colspan="7" class="alert alert-info">No products Found..</td>
      </tr>
      @endif

    </tbody>

  </table>
</div>
<div class="row">
  <div class="col-md-12">
    {{$products->links()}}
  </div>
</div>
@endsection
 
@section('scripts')
<script type="text/javascript">
  function confirmDelete(id){
    let choice = confirm("Are You sure, You want to Delete this Product ?")
    if(choice){
      document.getElementById('delete-product-'+id).submit();
    }
  }

</script>
@endsection