routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Frontend Routes
Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
  Route::get('/', 'ProductController@show')->name('all');
  Route::get('/{product}','ProductController@singlepro')->name('singlepro');
  Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('addToCart');
});


// Admin Panel Route
Route::group(['as' => 'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function () {
  Route::get('category/{category}/remove', 'CategoryController@remove')->name('category.remove');
  Route::get('category/trash', 'CategoryController@trash')->name('category.trash');
  Route::get('category/recover/{id}', 'CategoryController@recoverCat')->name('category.recover');
  Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');

  Route::get('product/{product}/remove', 'ProductController@remove')->name('product.remove');
  Route::get('product/trash', 'ProductController@trash')->name('product.trash');
  Route::get('product/recover/{id}', 'ProductController@recoverProduct')->name('product.recover');

  Route::view('product/extras', 'admin.partials.extras')->name('product.extras');

  Route::get('profile/{profile}/remove', 'ProfileController@remove')->name('profile.remove');
  Route::get('profile/trash', 'ProfileController@trash')->name('profile.trash');
  Route::get('profile/recover/{id}', 'ProfileController@recoverprofile')->name('profile.recover');
  Route::view('profile/roles', 'admin.partials.extras')->name('profile.extras');

  Route::get('profile/states/{id?}', 'ProfileController@getStates')->name('profile.states');
  Route::get('profile/cities/{id?}', 'ProfileController@getCities')->name('profile.cities');

  Route::resource('product', 'ProductController');
  Route::resource('category', 'CategoryController');
  Route::resource('profile', 'ProfileController');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Product;

class Category extends Model
{
  use SoftDeletes;
  protected $guarded = [];
  protected $dates = ['deleted_at'];
  //
  public function products(){
    return $this->belongsToMany("App\Product");
  }

  public function childrens(){
    return $this->belongsToMany(Category::class, 'category_parent', 'category_id', 'parent_id');
  }

  public function getRouteKeyName(){
    return 'slug';
  }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
  /**
   * Display a listing of the resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function index()
  {
    $categories = Category::paginate(3);
    return view('admin.categories.index', compact('categories'));
  }

  public function trash()
  {
    $categories = Category::onlyTrashed()->paginate(3);
    return view('admin.categories.index', compact('categories'));
  }

  /**
   * Show the form for creating a new resource.
   *
   * @return \Illuminate\Http\Response
   */
  public function create()
  {
    $categories = Category::all();
    return view('admin.categories.create', compact('categories'));
  }

  /**
   * Store a newly created resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @return \Illuminate\Http\Response
   */
  public function store(Request $request)
  {
    $request->validate([
      'title' => 'required|min:5',
      'slug' => 'required|min:5|unique:categories'
    ]);
    $categories = Category::create($request->only('title', 'description', 'slug'));
    $categories->childrens()->attach($request->parent_id);
    return back()->with('message', 'Category Added Successfully!');
  }

  /**
   * Display the specified resource.
   *
   * @param  \App\Category  $category
   * @return \Illuminate\Http\Response
   */
  public function show(Category $category)
  {
        //
  }

  /**
   * Show the form for editing the specified resource.
   *
   * @param  \App\Category  $category
   * @return \Illuminate\Http\Response
   */
  public function edit(Category $category)
  {
    $categories = Category::where('id', '!=', $category->id)->get();
    return view('admin.categories.create', ['categories' => $categories, 'category' => $category]);
  }

  /**
   * Update the specified resource in storage.
   *
   * @param  \Illuminate\Http\Request  $request
   * @param  \App\Category  $category
   * @return \Illuminate\Http\Response
   */
  public function update(Request $request, Category $category)
  {
    $this->validate($request, [
      'title' => 'required|min:5',
      'description' => 'required',
      'slug' => 'required|min:5'
    ]);
    $category->title = $request->title;
    $category->description = $request->description;
    $category->slug = $request->slug;
    //deattach all parent category
    $category->childrens()->detach();
    //attache selected parent category
    $category->childrens()->attach($request->parent_id);
    //save current record
    $saved = $category->save();
    //return back 
    return back()->with('message', 'Record Successfully Updated!');
  }

  public function recoverCat($id)
  {
    $category = Category::onlyTrashed()->findOrFail($id);
    if ($category->restore()) {
      return back()->with('message', 'Category Successfully Deleted!');
    } else {
      return back()->with('message', 'Errors from deleted item!');
    }
  }

  /**
   * Remove the specified resource from storage.
   *
   * @param  \App\Category  $category
   * @return \Illuminate\Http\Response
   */
  public function destroy(Category $category)
  {
    // Category::where('id', $id)->delete();
    // return back()->with('message', 'Record Successfully Deleted!');
    // return redirect()->back();
    if ($category->childrens()->detach() && $category->forceDelete()) {
      return back()->with('message', 'Category Successfully Deleted!');
    } else {
      return back()->with('message', 'Error Deleting Record');
    }
  }

  public function remove(Category $category)
  {
    if ($category->delete()) {
      return back()->with('message', 'Category Successfully Trashed!');
    } else {
      return back()->with('message', 'Error Deleting Record');
    }
  }
}

resources/views/admin/categories/create.blade.php
@extends('admin.app') {{-- 
@section('breadcrumbs')
<li class="breadcrumb-item">
  <a href="{{route('admin.dashboard')}}">Dashboard</a>
</li>
<li class="breadcrumb-item">
  <a href="{{route('admin.category.index')}}">Categories</a>
</li>
<li class="breadcrumb-item active" aria-current="page">Add/Edit Category</li>
@endsection
 --}} 
@section('content')
</div>
<form action="@if(isset($category)) {{route('admin.category.update', $category->id)}} @else {{route('admin.category.store')}} @endif"
  method="POST" accept-charset="utf-8">
  @csrf @if (isset($category)) @method('PUT') @endif
  <div class="form-group row">
    <div class="col-sm-12">
      @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
          @foreach ($errors->all() as $error)
          <li>{{ $error }}</li>
          @endforeach
        </ul>
      </div>
      @endif
    </div>
    <div class="col-sm-12">
      @if (session()->has('message'))
      <div class="alert alert-success">
        {{session('message')}}
      </div>
      @endif
    </div>
    <div class="col-sm-12">
      <label class="form-control-label">Title:</label>
      <input type="text" id="txturl" name="title" class="form-control" value="{{@$category->title}}">
      <p class="small">{{config('app.url')}}<span id="url">{{@$category->slug}}</span>
      </p>
      <input type="hidden" name="slug" id="slug" value="{{@$category->slug}}">
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-12">
      <label class="form-control-label">Description:</label>
      <textarea name="description" id="editor" cols="70" rows="10" class="form-control">{!! @$category->description !!}</textarea>
    </div>
  </div>

  {{--
  <div class="form-group row">
    <div class="col-sm-12">
      <label class="form-control-label">Select Category: </label>
      <select name="parent_id[]" id="parent_id" class="form-control" multiple="multiple">
        @if(isset($categories))
        <option value="0">Top Level</option>
        @foreach($categories as $cat)
        <option value="">{{$cat->title}}</option>
        @endforeach @endif option
      </select>
    </div>
  </div> --}}
  <div class="form-group row">
    @php $ids = (isset($category->childrens) && $category->childrens->count() > 0) ? array_pluck($category->childrens, 'id')
    : null 
@endphp
    <div class="col-sm-12">
      <label class="form-control-label">Select Category:</label>
      <select name="parent_id[]" id="parent_id" class="form-control" multiple>
        @if (isset($categories))
        <option value="0">Top Level</option>
        option @foreach ($categories as $cat)
        <option value="{{$cat->id}}" @if(isset($ids) && in_array($cat->id, $ids)) {{'selected'}} @endif>{{$cat->title}}</option>
        @endforeach @endif
      </select>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-12">
      @if (isset($category))
      <input type="submit" name="submit" value="Edit Category" class="btn btn-primary" /> @else
      <input type="submit" name="submit" value="Add Category" class="btn btn-primary" /> @endif
    </div>
  </div>
</form>
@endsection
 
@section('scripts')
<script type="text/javascript">
  $(function () {
    ClassicEditor.create(document.querySelector('#editor'),
      {
        toolbar: ['Heading', 'Link', 'bold', 'italic', 'bulletedList', 'numberedList', 'blockQuote', 'undo', 'redo'],
      }).then(editor => {
        console.log(editor);
      }).catch(error => {
        console.error(error);
      });
    $('#txturl').on('keyup', function () {
      var url = slugify($(this).val());
      $('#url').html(url);
      $('#slug').val(url);
    });
    $('#parent_id').select2({
      placeholder: "Select a Parent Category",
      allowClear: true,
      minimumResultsForSearch: Infinity
    });
  })

</script>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.app') 
@section('content')
</div>
<div class="col-sm-12">
  @if (session()->has('message'))
  <div class="alert alert-success">
    {{session('message')}}
  </div>
  @endif
</div>
<div class="row">
  <div class="col-sm-12">
    <a href="{{route('admin.category.create')}}" class="btn btn-primary float-right">Add Category</a>
  </div>
</div>
<div class="table-responsive pt-2">
  <table class="table table-striped table-sm">
    <thead>
      <tr>
        <th>S.N</th>
        <th>Title</th>
        <th>Description</th>
        <th>Slug</th>
        <th>Categories</th>
        <th>Created At</th>
        <th class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      @if ($categories) @foreach ($categories as $category)
      <tr>
        <td>{{$category->id}}</td>
        <td>{{$category->title}}</td>
        <td>{!! htmlspecialchars_decode($category->description) !!}</td>
        <td>{{$category->slug}}</td>
        <td>
          @if ($category->childrens()->count() > 0) @foreach ($category->childrens as $children) {{$children->title}}, @endforeach
          @else
          <strong>{{"Parent Category"}}</strong> @endif
        </td>
        @if($category->trashed())
        <td>{{$category->created_at}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('admin.category.recover',$category->id)}}">Restore</a> | <a class="btn btn-danger btn-sm"
            href="javascript:;" onclick="confirmDelete('{{$category->id}}')">Delete</a>
          <form id="delete-category-{{$category->id}}" action="{{ route('admin.category.destroy', $category->id) }}" method="POST"
            style="display: none;">
            @method('DELETE') @csrf
          </form>
        </td>
        @else
        <td>{{$category->created_at}}</td>
        <td><a class="btn btn-info btn-sm" href="{{route('admin.category.edit',$category->slug)}}">Edit</a> | <a id="trash-category-{{$category->id}}"
            class="btn btn-warning btn-sm" href="{{route('admin.category.remove',$category->slug)}}">Trash</a> | <a class="btn btn-danger btn-sm"
            href="javascript:;" onclick="confirmDelete('{{$category->slug}}')">Delete</a>
          <form id="delete-category-{{$category->slug}}" action="{{ route('admin.category.destroy', $category->slug) }}" method="POST"
            style="display: none;">
            @method('DELETE') @csrf
          </form>
        </td>
        @endif
      </tr>
      @endforeach @else
      <tr>
        <td colspn="5">No Categories Found..</td>
      </tr>
      @endif
    </tbody>
  </table>
</div>
<div class="row">
  <div class="col-md-12">
    {{$categories->links()}}
  </div>
</div>
@endsection
 
@section('scripts')
<script type="text/javascript">
  function confirmDelete(id){ 
    let choice = confirm("Are You sure, You want to Delete this record ?") 
    if(choice){ 
      document.getElementById('delete-category-'+id).submit();
    } 
  }

</script>
@endsection