routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', function () {
  return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

// Frontend Routes
Route::group(['as' => 'products.', 'prefix' => 'products'], function () {
  Route::get('/', 'ProductController@show')->name('all');
  Route::get('/{product}','ProductController@singlepro')->name('singlepro');
  Route::get('/addToCart/{product}', 'ProductController@addToCart')->name('addToCart');
});


// Admin Panel Route
Route::group(['as' => 'admin.', 'middleware' => ['auth', 'admin'], 'prefix' => 'admin'], function () {
  Route::get('category/{category}/remove', 'CategoryController@remove')->name('category.remove');
  Route::get('category/trash', 'CategoryController@trash')->name('category.trash');
  Route::get('category/recover/{id}', 'CategoryController@recoverCat')->name('category.recover');
  Route::get('dashboard', 'AdminController@dashboard')->name('dashboard');

  Route::get('product/{product}/remove', 'ProductController@remove')->name('product.remove');
  Route::get('product/trash', 'ProductController@trash')->name('product.trash');
  Route::get('product/recover/{id}', 'ProductController@recoverProduct')->name('product.recover');

  Route::view('product/extras', 'admin.partials.extras')->name('product.extras');

  Route::get('profile/{profile}/remove', 'ProfileController@remove')->name('profile.remove');
  Route::get('profile/trash', 'ProfileController@trash')->name('profile.trash');
  Route::get('profile/recover/{id}', 'ProfileController@recoverprofile')->name('profile.recover');
  Route::view('profile/roles', 'admin.partials.extras')->name('profile.extras');

  Route::get('profile/states/{id?}', 'ProfileController@getStates')->name('profile.states');
  Route::get('profile/cities/{id?}', 'ProfileController@getCities')->name('profile.cities');

  Route::resource('product', 'ProductController');
  Route::resource('category', 'CategoryController');
  Route::resource('profile', 'ProfileController');
});

resources/views/admin/partials/extra.blade.php
@if (request()->ajax())
<div class="row align-items-center options">
  <div class="col-sm-4">
    <label class="form-control-label">Option <span class="count">1</span></label>
    <input type="text" name="option[]" class="form-control" value="" placeholder="size">
  </div>
  <div class="col-sm-8">
    <label class="form-control-label">Values</label>
    <input type="text" name="values[]" class="form-control" placeholder="options1 | option2 | option3" />
    <label class="form-control-label">Additional Prices</label>
    <input type="text" name="prices[]" class="form-control" placeholder="price1 | price2 | price3" />
  </div>
</div>
@else
<p class="alert alert-danger">You Can Not Access Directly!!</p>
@endif

resources/views/admin/partials/footer.blade.php
<!-- Icons -->
{{--
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
  feather.replace()

</script> --}}
<script src="{{asset('js/app.js')}}"></script>

resources/views/admin/partials/head.blade.php
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- CSRF Token -->
  <meta name="csrf-token" content="{{ csrf_token() }}">

  <title>{{ config('app.name', 'E-Commerce') }}</title>


  <!-- Fonts -->
  <link rel="dns-prefetch" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

  <!-- Styles -->
  <link href="{{ asset('css/app.css') }}" rel="stylesheet">
  <link rel="stylesheet" href="{{asset('css/admin.css')}}">
</head>

resources/views/admin/partials/navbar.blade.php
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{{route('admin.dashboard')}}">Company name</a>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link" href="#">Sign out</a>
    </li>
  </ul>
</nav>

<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 d-none d-md-block bg-light sidebar">
      <div class="sidebar-sticky">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link @if(request()->url() == route('admin.dashboard')) {{'active'}} @endif" href="{{url('/admin/dashboard')}}">
                  <span data-feather="home"></span>
                  Dashboard <span class="sr-only">(current)</span>
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="file"></span>
                  Orders
                </a>
          </li>
          <li class="nav-item dropdown">
            <a id="productDropdown" class="nav-link @if(request()->url() == route('admin.product.index')) {{'active'}} @endif  dropdown-toggle"
              href="javascript:;" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <span data-feather="shopping-cart"></span>
                  Products
                </a>
            <div class="dropdown-menu" aria-labelledby="productDropdown">
              <a class="dropdown-item" href="{{route('admin.product.create')}}">Add Product</a>
              <a class="dropdown-item" href="{{route('admin.product.index')}}">All Products</a>
              <a class="dropdown-item" href="{{route('admin.product.trash')}}">Trashed Products</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a id="categoryDropdown" class="nav-link @if(request()->url() == route('admin.category.index')) {{'active'}} @else {{''}} @endif dropdown-toggle"
              href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span data-feather="bar-chart-2"></span>
              Categories
            </a>
            <div class="dropdown-menu" aria-labelledby="categoryDropdown">
              <a class="dropdown-item" href="{{route('admin.category.create')}}">Add Category</a>
              <a class="dropdown-item" href="{{route('admin.category.index')}}">All Categories</a>
              <a class="dropdown-item" href="{{route('admin.category.trash')}}">Trashed Categories</a>
            </div>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{route('admin.profile.index')}}">
                  <span data-feather="users"></span>
                  Customers
             </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="layers"></span>
                  Integrations
                </a>
          </li>
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="d-flex align-items-center text-muted" href="#">
                <span data-feather="plus-circle"></span>
              </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Current month
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Last quarter
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Social engagement
                </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
                  <span data-feather="file-text"></span>
                  Year-end sale
                </a>
          </li>
        </ul>
      </div>
    </nav>